### ISSUE TITLE
Directory structure for CamVid dataset.

### ISSUE THREAD

**Issue by shriyanka** [e-lab/LinkNet#1]
Hello,

Can you please provide the directory structure for CamVid dataset for training purpose like one described for training Enet as [here](https://github.com/e-lab/ENet-training/blob/master/train/data/README.md)

**Comment by codeAC29** [comment]
@shriyanka Thank you for bringing it up. Hope 72cc3fc commit helps.

**Comment by shriyanka** [comment]
Thanks @codeAC29. Its very helpful.
