### ISSUE TITLE
Torch: not enough memory (17GB)

### ISSUE THREAD

**Issue by amiltonwong** [e-lab/LinkNet#6]
Hi, all

When I run :
`
th main.lua --datapath /data2/cityscapes_dataset/leftImg8bit/all_train_images/ --cachepath /data2/cityscapes_dataset/leftImg8bit/dataCache/ --dataset cs --model models/model.lua --save save_models/cityscapes/ --saveTrainConf --saveAll --plot
`

I got "Torch: not enough memory: you tried to allocate 17GB" error ([details](https://gist.github.com/amiltonwong/c1c6011a84c218ad6fcaf0eb5c7c70ad))

It's strange because the paper mentioned it is trained using Titan X which has 12GB memory. Why the network consumes 17GB in running? 

Any suggestion to fix this issue?

Thanks!

**Comment by codeAC29** [comment]
@amiltonwong check your input image size and batch size. For cityscapes it should be `512x1024` and 10 respectively.

**Comment by amiltonwong** [comment]
Hi, @codeAC29 ,

Could I resize the input image using your package or other tools such as PIL or OpenCV?

**Comment by codeAC29** [comment]
The training script will automatically resize it for you. Just use `imHeight` and `imWidth` option while training.
